# CMake generated Testfile for 
# Source directory: D:/dev/guideXOS_Hypervisor
# Build directory: D:/dev/guideXOS_Hypervisor/.codex_tmp/build-final-vs-clean
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(BasicTests "D:/dev/guideXOS_Hypervisor/.codex_tmp/build-final-vs-clean/bin/Debug/ia64emu_tests.exe")
  set_tests_properties(BasicTests PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Hypervisor/CMakeLists.txt;559;add_test;D:/dev/guideXOS_Hypervisor/CMakeLists.txt;0;")
else()
  add_test(BasicTests NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(NewInstructionTests "D:/dev/guideXOS_Hypervisor/.codex_tmp/build-final-vs-clean/bin/Debug/test_new_instructions.exe")
  set_tests_properties(NewInstructionTests PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Hypervisor/CMakeLists.txt;560;add_test;D:/dev/guideXOS_Hypervisor/CMakeLists.txt;0;")
else()
  add_test(NewInstructionTests NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(SyscallTests "D:/dev/guideXOS_Hypervisor/.codex_tmp/build-final-vs-clean/bin/Debug/test_syscall_dispatcher.exe")
  set_tests_properties(SyscallTests PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Hypervisor/CMakeLists.txt;561;add_test;D:/dev/guideXOS_Hypervisor/CMakeLists.txt;0;")
else()
  add_test(SyscallTests NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(DebuggerTests "D:/dev/guideXOS_Hypervisor/.codex_tmp/build-final-vs-clean/bin/Debug/test_debugger.exe")
  set_tests_properties(DebuggerTests PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Hypervisor/CMakeLists.txt;562;add_test;D:/dev/guideXOS_Hypervisor/CMakeLists.txt;0;")
else()
  add_test(DebuggerTests NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(ProfilerTests "D:/dev/guideXOS_Hypervisor/.codex_tmp/build-final-vs-clean/bin/Debug/test_profiler.exe")
  set_tests_properties(ProfilerTests PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Hypervisor/CMakeLists.txt;563;add_test;D:/dev/guideXOS_Hypervisor/CMakeLists.txt;0;")
else()
  add_test(ProfilerTests NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(FuzzerTests "D:/dev/guideXOS_Hypervisor/.codex_tmp/build-final-vs-clean/bin/Debug/test_fuzzer.exe")
  set_tests_properties(FuzzerTests PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Hypervisor/CMakeLists.txt;564;add_test;D:/dev/guideXOS_Hypervisor/CMakeLists.txt;0;")
else()
  add_test(FuzzerTests NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(VMIsolationTests "D:/dev/guideXOS_Hypervisor/.codex_tmp/build-final-vs-clean/bin/Debug/test_vm_isolation.exe")
  set_tests_properties(VMIsolationTests PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Hypervisor/CMakeLists.txt;565;add_test;D:/dev/guideXOS_Hypervisor/CMakeLists.txt;0;")
else()
  add_test(VMIsolationTests NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(RiscVDecoderSmokeTest "D:/dev/guideXOS_Hypervisor/.codex_tmp/build-final-vs-clean/bin/Debug/test_riscv_decoder.exe")
  set_tests_properties(RiscVDecoderSmokeTest PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Hypervisor/CMakeLists.txt;566;add_test;D:/dev/guideXOS_Hypervisor/CMakeLists.txt;0;")
else()
  add_test(RiscVDecoderSmokeTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(ELFValidationTests "D:/dev/guideXOS_Hypervisor/.codex_tmp/build-final-vs-clean/bin/Debug/test_elf_validation.exe")
  set_tests_properties(ELFValidationTests PROPERTIES  _BACKTRACE_TRIPLES "D:/dev/guideXOS_Hypervisor/CMakeLists.txt;567;add_test;D:/dev/guideXOS_Hypervisor/CMakeLists.txt;0;")
else()
  add_test(ELFValidationTests NOT_AVAILABLE)
endif()
